# Generated by Django 3.1.3 on 2020-12-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201203_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBlog',
            fields=[
                ('post_id1', models.AutoField(primary_key=True, serialize=False)),
                ('title1', models.CharField(max_length=50)),
                ('desc1', models.CharField(max_length=500)),
                ('name1', models.CharField(max_length=20)),
                ('date1', models.DateField()),
                ('image1', models.ImageField(upload_to='blog/images')),
            ],
        ),
    ]
