# Generated by Django 3.1.3 on 2020-12-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newblog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newblog',
            name='date1',
        ),
    ]
